# Generated by Django 4.1.4 on 2023-03-23 13:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=10)),
                ('zip', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('special_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('dd_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Delivery Detail',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50, unique=True)),
                ('d_desc', models.CharField(blank=True, max_length=1000)),
                ('d_image', models.ImageField(default='/static/images/lion-fish.jpg', upload_to='static/images')),
                ('d_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('products_amount', models.PositiveIntegerField(default=0)),
                ('products_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_product_amount', models.PositiveIntegerField(default=0)),
                ('o_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Orders1',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, unique=True)),
                ('p_desc', models.CharField(blank=True, max_length=1000)),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('p_amount', models.PositiveIntegerField()),
                ('p_image', models.ImageField(default='/static/images/lion-fish.jpg', upload_to='static/images')),
                ('p_created', models.DateField(auto_now_add=True)),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.department')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_created', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, null=True, to='shopapp.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('r_created', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.profile')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.order1')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
            options={
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.AddField(
            model_name='order1',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.profile'),
        ),
        migrations.AddField(
            model_name='order1',
            name='delivery_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.deliverydetail'),
        ),
        migrations.AddField(
            model_name='order1',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='shopapp.OrderProduct', to='shopapp.product'),
        ),
    ]
