# Generated by Django 4.1.4 on 2023-03-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='products_price',
        ),
    ]
