# Generated by Django 4.1.4 on 2023-03-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_order1_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount_selected',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
