# Generated by Django 4.1.4 on 2023-03-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_orderproduct_amount_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='products_amount',
        ),
    ]
