# Generated by Django 4.1.4 on 2023-03-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_order1_products_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order1',
            name='products_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
