# Generated by Django 4.1.4 on 2023-03-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_order1_products_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='delivery_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.deliverydetail'),
        ),
    ]
